### ISSUE TITLE
Check Travis CI settings

### ISSUE THREAD

**Issue by johnzeringue** [bowring/Calamari#18]
It seems like "build pushes" might be disabled in Travis CI. This allows weird situations where a pull request that builds successfully can break `master` without notice from Travis after being merged.

"Build pushes" can be configured in the repository settings on [travis-ci.org](https://travis-ci.org).

**Comment by bowring** [comment]
thanks, fixed

On Wed, Jul 13, 2016 at 4:58 PM, John Zeringue <notifications@github.com>
wrote:

> It seems like "build pushes" might be disabled in Travis CI. This allows
> weird situations where a pull request that builds successfully can break
> master without notice from Travis after being merged.
>
> "Build pushes" can be configured in the repository settings on
> travis-ci.org.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bowring/Calamari/issues/18>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABCtY4-DjWZ5-Lmb4AgbE34g4qQnw0-Nks5qVVGRgaJpZM4JL17R>
> .
>



-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org, www.github.com/cirdles
GitHub: https://github.com/bowring

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.
